### PR TITLE
Fix nuget warns on master

### PR DESCRIPTION
**Pull request by andreasohlund**

### CODE REVIEW

**Comment by andreasohlund** [comment]
@Particular/msmq-transport-maintainers are you happy with this approach to patch master but not release anything?

**Comment by dvdstelt** [comment]
Absolutely

**Comment by andreasohlund** [comment]
@timbussmann I think its ok to squash merge this one to avoid GVT to rev the version?

**Comment by timbussmann** [comment]
we definitely did so before although I'm not sure whether this is really allowed by Gitflow.

**Pull request merged**
