### PR TITLE
Update test projects to NServiceBus 7.1

### PR DESCRIPTION
**Pull request by timbussmann**

### CODE REVIEW

**Comment by andreasohlund** [comment]
Comple fails with 

```
Open in IDE
C:\Program Files\dotnet\sdk\2.1.401\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(199, 5): error NU5110: The script file 'build\CreateQueues.ps1' is outside the 'tools' folder and hence will not be executed during installation of this package. Move it into the 'tools' folder.
C:\Program Files\dotnet\sdk\2.1.401\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(199, 5): error NU5110: The script file 'build\DeleteQueues.ps1' is outside the 'tools' folder and hence will not be executed during installation of this package. Move it into the 'tools' folder.
C:\Program Files\dotnet\sdk\2.1.401\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(199, 5): error NU5111: The script file 'build\CreateQueues.ps1' is not recognized by NuGet and hence will not be executed during installation of this package. Rename it to install.ps1, uninstall.ps1 or init.ps1 and place it directly under 'tools'.
C:\Program Files\dotnet\sdk\2.1.401\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(199, 5): error NU5111: The script file 'build\DeleteQueues.ps1' is not recognized by NuGet and hence will not be executed during installation of this package. Rename it to install.ps1, uninstall.ps1 or init.ps1 and place it directly under 'tools'.
```

Is that a new thing? cc @bording

**Comment by timbussmann** [comment]
From my understanding, we need to suppress this warning, as these scripts are not intended to run at package installation time @andreasohlund ?

**Comment by andreasohlund** [comment]
Will you suppress the warning?

**Comment by timbussmann** [comment]
yes, will update the PR. Just wanted to get this confirmed from a MSMQ maintainer :)

**Pull request merged**
